######################################################################
# Automatically generated by qmake (3.0) Wed Apr 6 21:29:01 2016
######################################################################

TEMPLATE = app
TARGET = qhash
INCLUDEPATH += .

QT += widgets \
      sql

# Input
SOURCES += qhash.cpp
