######################################################################
# Automatically generated by qmake (3.0) Wed Apr 27 21:33:55 2016
######################################################################

TEMPLATE = app
TARGET = localsocket
INCLUDEPATH += .

QT += network

# Input
SOURCES += localsocket.cpp
